### ISSUE TITLE
A bug  in unquote-splicing

### ISSUE THREAD

**Issue by nixxon** [biwascheme/biwascheme#101]
According to Kent Dybvig's book "The Scheme Programming Language" 4th edition (see example [here](http://www.scheme.com/tspl4/objects.html#./objects:h1)) this code
```
(let ((a 1) (b 2))
   `(,a ,@b))
```
should evaluate to `(1 . 2) `.

But, in BiwaScheme this expression produces an error: **ar[k].to_array is not a function [(anon), append]**

**Comment by yhara** [comment]
Confirmed with git master.
