### ISSUE TITLE
read in biwascheme

### ISSUE THREAD

**Issue by ta2gch** [biwascheme/biwascheme#105]
Hello, I'm TANIGUCHI Masaya.
I notice you that I can add `read` to biwascheme.

Yesterday, I got the success to execute `read` in [my implementation](https://github.com/ta2gch/iris). Please see this [webpage](https://islisp.js.org). This is a ISLisp implementation works on Go / JavaScript. We can use `read` in this REPL. To do this in your implementation,

1. Build REPL with gopherjs instead of JavaScript
2. Use goroutines and channels to block and get input string
3. Returns strings as streams

For more infomations, see [my repository](https://github.com/ta2gch/islisp.js.org)

I hope this news makes your project better.

Cheers.

I sent [same issue in JSCL](https://github.com/jscl-project/jscl/issues/287).

**Comment by ta2gch** [comment]
I close this issue because of https://github.com/jscl-project/jscl/issues/287#issuecomment-329064681

**Comment by yhara** [comment]
Hmm, looks like current implementation of `read` is broken. It should use `BiwaScheme.Pause`.

**Comment by yhara** [comment]
Made #106
