### ISSUE TITLE
`read` should use BiwaScheme.Pause

### ISSUE THREAD

**Issue by yhara** [biwascheme/biwascheme#106]
It should be a "blocking" function, like `sleep`.

**Comment by ta2gch** [comment]
Hi @yhara, Is my issue #105  is **not** wrong? I have thought the behavior has been already known by you.

**Comment by yhara** [comment]
Yes, this is a bug.

- What I tried
  - Open http://www.biwascheme.org and type `(read)` and press Enter
- What I expected
  - The repl waits for my input
  - After writing a sexp, repl prints result of `(read)`
- Actual behavior
  - Prompt is shown immediately

**Comment by ta2gch** [comment]
Thank you for your explanation. I see  BiwaScheme had a `read` and doesn't work now. I have understand that you are going to fix this issue at BiwaScheme.Pause.  I'm looking forward to fixing it.
