### ISSUE TITLE
Feature request: (random) function

### ISSUE THREAD

**Issue by Masterxilo** [biwascheme/biwascheme#109]
I am working my way through SICP (running programs via repl.it) and they use this alias for (random-integer).

Other people have had the same issue: https://stackoverflow.com/questions/27743009/random-in-biwascheme-scheme

**Comment by yhara** [comment]
I'm not going to add non-standard functions to Biwa, but instead there is a guide to run SICP code on Biwa. https://www.biwascheme.org/doc/sicp.html
