### ISSUE TITLE
why it only  work once time

### ISSUE THREAD

**Issue by angsheng** [biwascheme/biwascheme#111]
i want to do a html page like REPL,a <input>for input text,when click thebutton will create a <script src="./biwascheme.js"> and get the input value,i try it but only work  the first  time click.
i try this method with other scripts  is no problems

**Comment by yhara** [comment]
Hi,

I'm not sure what problem you are facing. Can you upload the code you wrote?

**Comment by angsheng** [comment]
sorry,too late to this ,
i solved this problem ,it is from the same javascript file only run once in browser, my code want to reload the scripts to complie ,so that failed.
thank you for your respons. so glad  :)

**Comment by angsheng** [comment]
i solved this problem ,it is from the same javascript file only run once in browser, my code want to reload the scripts to complie ,so that failed.
thank you for your respons. so glad :)

**Comment by yhara** [comment]
👍
