### ISSUE TITLE
Website repl should support `(read)`

### ISSUE THREAD

**Issue by yhara** [biwascheme/biwascheme#113]
refs: #106

This should be fixed by defining `current_input` like [the one for Node.js](https://github.com/biwascheme/biwascheme/blob/d04677b41a584a608ca8264e16e1f189ac0a284b/src/platforms/node/module_postamble.js#L60-L73) to website/js/biwascheme_terminal.js , but I'm not sure what it would be like.

```
    BiwaScheme.Port.current_input = new BiwaScheme.Port.CustomInput(function(callback){
        ??
    });
```

**Comment by jcubic** [comment]
in jQuery Terminal to have read you can use:

```javascript
term.push(function(string) {
    // this will be executed when user press enter without shift
   term.pop();
}, {prompt: ''});
```
I've tested on the website and this work
```javascript
    BiwaScheme.Port.current_input = new BiwaScheme.Port.CustomInput(function(callback){
        term.push(function(str) { callback(str); term.pop(); }, {prompt: ''});
    });
```


you have very old version that was adding space to prompt and if you push new interpreter the prompt is not changed if you press enter (but the function is working), to fix those you will need update jQuery Terminal but you will need to use space after prompt: `prompt: 'biwascheme> '`.

if you use latest version you can use shorthand function read:

```javascript
    BiwaScheme.Port.current_input = new BiwaScheme.Port.CustomInput(function(callback){
        term.read('', callback);
    });
```
