### ISSUE TITLE
Button names don't update properly

### ISSUE THREAD

**Issue by siraben** [biwascheme/biwascheme#114]
I made a small game in Biwascheme, and one of the bugs I have encountered is with dynamically updating the button labels. A demo of the game can be found [here](https://siraben.github.io/brownies/).

Click on the "Buy Factory" button and notice that the cost changes, but the same does not work with the other buttons.

The Scheme source can be viewed by using the developer tools or by clicking [here](https://github.com/siraben/brownies/blob/master/game.scm).

After some testing it seems that correct button updates happen on the most recently created button, so perhaps a bug in BiwaScheme is causing the local button variable in the `let` statement (shown below, fragment of [full source](https://github.com/siraben/brownies/blob/master/game.scm)) to be lost when another purchase object is created with the `make-new-purchase` function.

```scheme
(define (make-new-purchase name price cps interest)
  (let ((amount 0)
        (cost price)
        (button
         (create-button (string-append "Buy " name " (" (number->string price) ")"))))

    (js-invoke button "setAttribute" "title" (string-append "Gets " (number->string cps)" clicks per second."))

    (define (buy)
      (if (> cost *num-brownies*)
          (message! (string-append "Insufficient funds! You need " (number->string (2dec cost)) " brownies."))

          (begin 
            (set! *num-brownies* (- *num-brownies* cost))
            (set-timer! click (/ 1 cps))
            (set! amount (+ amount 1))
            (set! cost (* price (expt interest amount)))
            (message! (string-append "Price of " name " now at " (number->string (2dec cost)) " brownies."))
            (refresh))))

    (bind-proc-button button buy)

    (define (refresh)
      (begin (set! cost (* price (expt interest amount)))
             ;; Button name fails to update unless it is most recently instantiated object.
             (name-button! button (string-append "Buy " name " (" (number->string (2dec cost)) ")" ))))

    (define (dispatch m)
      (cond ((eq? m 'refresh) refresh)
            ((eq? m 'buy) buy)
            ((eq? m 'get-amount) amount)))
    dispatch))

```

**Comment by yhara** [comment]
Hi,

> Click on the "Buy Factory" button and notice that the cost changes, but the same does not work with the other buttons.

When I clicked "Buy mine", I see "Price of mine now at 1150 brownies". 
And by clicking it again, I see "Price of mine now at 1322.49 brownies".
So it looks like the cost is properly changed to me, but is it not what you expect?

https://gyazo.com/a6cab00675c383450b96f1908ad5c126
Tested with Mac Chrome 64 and Firefox 58.

**Comment by siraben** [comment]
Hi and thanks for responding.

What I meant was the button labels (i.e. the text on the button itself) didn't change. Try buying a factory first and see the price change on the button itself.

The exact same code is used to generate all buttons, so I think it's a bug in BiwaScheme.

**Comment by yhara** [comment]
> What I meant was the button labels (i.e. the text on the button itself) didn't change.

Hmm, I see. I will investigate.

**Comment by yhara** [comment]
I think it's fixed by https://github.com/siraben/brownies/pull/1 , but it should raise error rather than failing silently (Filed as #116). Thanks for reporting!
