### ISSUE TITLE
string->number conversion

### ISSUE THREAD

**Issue by pedro-gutierrez** [biwascheme/biwascheme#115]
Hi, I am still quite new to Scheme, however I was wondering whether this is a bug?

biwascheme> (number? (string->number "1"))
#t

biwascheme> (number? (string->number "abc"))
#t

Tested on 0.6.8.

**Comment by yhara** [comment]
According to [R7RS](http://r7rs.org/), string->number should return #f for "abc". So this is a bug.

> If string is not a syntactically valid notation for a number, or would result in a number that the implemen- tation cannot represent, then string->number returns #f.

**Comment by yhara** [comment]
Closed by #119
