### ISSUE TITLE
Parenthesis matching in website REPL

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#124]
In [lips my scheme like lisp interpreter](https://jcubic.github.io/lips/) I've created nice feature when you're typing parenthesis it jumps for a second to matching parenthesis so it make easier to type S-Expressions.

The idea is from scheme interpreter they used in [SICP video lectures](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/video-lectures/).

You can incorporate this feature into REPL. I can send you updated biwascheme_terminal.js file if you want.

Another feature in my interpreter is scheme syntax highlighting.

**Comment by yhara** [comment]
Cool! It's definitely nice to have. I'd like to merge it if you send me a PR.

**Comment by yhara** [comment]
Closed by #133
