### ISSUE TITLE
Scheme REPL Terminal wrapping issue

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#126]
I've just found one issue with jQuery Terminal REPL, on official website home page, related to wildcard selector and font-family. I thought that the bug was fixed but it's still there when you calculate number of characters per line.

To replicate  the bug just try to type more characters, it don't wrap. To fix the issue you need version 2.1.1 or remove wildcard selector.

**Comment by jcubic** [comment]
The version 2.1.1 was broken I've left commented out one line that didn't remove temporary terminal div from body. So you need version 2.1.2.

**Comment by jcubic** [comment]
If you decided to update the library you can take a look at my new interpreter for my LIPS (simple scheme like lisp without big std lib like scheme)

It support:
* parenthesis matching
* syntax highlighting
* better multi line
* automatic indentation (paste code will auto indent each line)

Here is my interpreter: https://jcubic.github.io/lips/

You can try to copy/paste this code:
```
(((lambda (f)
((lambda (g) (g g))
(lambda (g)       
(f (lambda a (apply (g g) a))))))
(lambda (recur)
(lambda (n)
(if (== n 0)
1
(* n (recur (- n 1))))))) 10)
```
(inline Y combinator and factorial function)

If you have the site in git repo I can create PR.

**Comment by yhara** [comment]
> If you have the site in git repo I can create PR.

Thank you! https://github.com/biwascheme/biwascheme/tree/master/website is the source and you can preview it by this:

```
$ make
$ npm install
$ node local_website.js
$ open http://localhost:7001
```

**Comment by jcubic** [comment]
I've synced my old fork, I've run the commands but got `Cannot GET /index.html` and website directory have only some old `i.html` file there is records branch that look more up to date but it's not the same as on biwascheme.org website, or I do something wrong.

**Comment by jcubic** [comment]
it seems that website is in doc directory (it have markdown files) and you need `make website` an I correct?

**Comment by yhara** [comment]
> it seems that website is in doc directory (it have markdown files) and you need make website an I correct?

Oh that's right! I've [fixed](https://github.com/biwascheme/biwascheme/commit/2f58d0c881f34450d47470ce853f0d401b5640d5) the README.

**Comment by jcubic** [comment]
Maybe you should remove that website directory or rename it since part if the files came from index_.html part from docs directory.

*Other and better solution:* You can refactor this structure to have everything in one place. Maybe put index_.html and header footer into website directory and change path in Makefile, it will make more sens, since only output index.html is require to be in root directory, and docs files if they use those can get from `../website/`

**Comment by yhara** [comment]
> Maybe put index_.html and header footer into website directory and change path in Makefile, it will make more sens,

I agree. I've moved header and footer to `website/`.
