### ISSUE TITLE
Circular lists

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#136]
This code freezes the browser:
```
> (define xxx  (let ((x '(1 2 3))) (set-cdr! (cddr x) x) x))
> xxx
```

it don't work in guile though

but this works in guile:
```
(define x '(1 2 3))
(set-cdr! (cddr x) x)
x
=> (1 2 3 . #-2#)
```

it also freezes the browser when runs in biwascheme terminal.

**Comment by yhara** [comment]
You can use `write/ss` to print circular lists.

```
$ biwas
BiwaScheme version 0.6.9
try (+ 1 2), etc. (Ctrl-D to exit)
biwascheme> (define xxx  (let ((x '(1 2 3))) (set-cdr! (cddr x) x) x))
#<undef>
biwascheme> (write/ss xxx)
#0=(1 2 3 . #0#)#<undef>
biwascheme>
```

**Comment by jcubic** [comment]
Awesome this can be integrated with terminal use write/ss instead of normal print. I can create PR if you will merge my last one and actually use the code I've commit (my last PR is not online on website).

**Comment by yhara** [comment]
@jcubic ok I've just merged #135 and updated https://www.biwascheme.org/ 🎉

**Comment by jcubic** [comment]
Awesome, it look great.

**Comment by jcubic** [comment]
Not sure why but it don't work anymore:
this throw stack overload exception

```scheme
(let ((x '(1 2 3)))                  
  (set-cdr! (cddr x) (cons x x))
  x)
```

 and this freezes the browser:

```scheme
(let ((x '(1 2 3)))
  (set-cdr! (cddr x) x)
  x)
```

**Comment by yhara** [comment]
Confirmed with v0.7.0. This should be added to unit test 😕

**Comment by yhara** [comment]
Fixed 👍
