### ISSUE TITLE
[[Inquiry]] Async AJAX Calls with BiwaScheme

### ISSUE THREAD

**Issue by WammKD** [biwascheme/biwascheme#137]
Looking through the reference page, – under AJAX – it's mentioned being able to make synchronous calls via `http-get`, `http-post`, etc.

Is it possible to make asynchronous AJAX calls via BiwaScheme?

**Comment by yhara** [comment]
There is no stdlib to do it, but you can define your own like this.

```html
<script type="text/javascript">
BiwaScheme.define_libfunc("http-get-async", 2, 2, function(args, intp){
  $.get(args[0], function(data) {
    intp.invoke_closure(args[1], [data]);
  });
});
</script>

<script type="text/biwascheme">
(http-get-async "/index.html" (lambda (data)
  (alert data)))
</script>
```

**Comment by WammKD** [comment]
I never actually closed this; I'm sorry about that. Thanks a ton for the info. This was really helpful and directly helped me solve my problem.
