### ISSUE TITLE
Mobile website

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#139]
The website is not mobile friendly. try opening it on a phone. and in comparison check mine [LIPS](https://jcubic.github.io/lips/).

I've just added one feature to jQuery Terminal that will able to make `)` match parenthesis on mobile (because extra space was injected after `)`, it didn't work).

When new version of jQuery Terminal (2.6.0) is out I can try to create mobile version of the site if you want.

**Comment by jcubic** [comment]
You may also consider using CDN like unpkg or other for JS and CSS on my internet connection (desktop) Terminal js file loaded 13 seconds (it's unminified) and BiwaScheme loaded in 19 second, it's minfied but from same server maybe CDN will speed this up (maybe part of why it so slow is because server is in Japan and I'm in Europe).

Also script files block loading of the page because they are at the begning of the page, and page is black while scripts are loading adding to the end (before `</body>`) will load css and layout and only terminal will not show up while the files are downloaded.

**Comment by yhara** [comment]
> When new version of jQuery Terminal (2.6.0) is out I can try to create mobile version of the site if you want.

Thank you! Until then, I'll migrate the site from my VPS to github pages (#140). Hopefully it will improve     the loading time?

**Comment by jcubic** [comment]
It's much faster now.

**Comment by yhara** [comment]
Fixed by #142 😄
