### ISSUE TITLE
any update on the r7rs branch?

### ISSUE THREAD

**Issue by vidjuheffex** [biwascheme/biwascheme#144]
or an update on the WIP status of the define-syntax stuff. Would be nice to use implement some SRFI's that way over javascript implementations. Thanks

**Comment by yhara** [comment]
I once [tried](https://github.com/biwascheme/biwascheme/commits/0-7-x) to implement syntax-case but couldn't finish. Maybe retry this summer?

**Comment by vidjuheffex** [comment]
Would be awesome! Love this project

**Comment by yhara** [comment]
Update: I tried to finish syntax-case [last summer](https://github.com/biwascheme/biwascheme/tree/syntax-case) but concluded that "I can't debug this anymore" 😢 

Now I'm thinking about trying different approach (implement syntax-rules using syntactic-closure + explicit-renaming macro)

**Comment by vidjuheffex** [comment]
thanks for the update and good luck
