### ISSUE TITLE
'use strict'

### ISSUE THREAD

**Issue by yhara** [biwascheme/biwascheme#162]
It is better to enable strict mode of JavaScript.

However, there is an issue to do that:

- `make_assert` in `src/library/infra.js` relies on `arguments.callee`, which cannot be used in the strict mode

**Comment by amirouche** [comment]
What is the advantage of strict mode for biwascheme? It speed up JIT or something?

**Comment by yhara** [comment]
Mainly for better error checking.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
By the way this ticket should be closed because biwascheme is already in strict mode since #160 .
