### ISSUE TITLE
how to format float with 2 decimal places? 

### ISSUE THREAD

**Issue by Nixonite** [biwascheme/biwascheme#165]
Hi all,

I was wondering if biwascheme had some format functionality that would allow me to keep a variable as a float, yet print it with only a few decimal places without having to constantly apply (round) to it? 

Example: 

`(print (format "~0,2F" 0.2222))` would ideally print `"0.22"`

I couldn't find a way to do this

**Comment by yhara** [comment]
You can use [toFixed](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) via js-invoke.
```scm
biwascheme> (js-invoke 0.2222 "toFixed" 2)
"0.22"
```
