### ISSUE TITLE
A way to disable interop with host environment (JavaScript)

### ISSUE THREAD

**Issue by ceigey** [biwascheme/biwascheme#172]
Hi all,
I was wondering if it would be possible* to disable interop with JS and the web APIs from the BiwaScheme side (while still having access to the BiwaScheme API to obtain values)?

* (at least maybe in a personal fork, not necessarily as a PR) 

The motivation is to allow for user-defined scripting that is relatively sandboxed (e.g. no access to prototypes, DOM, network, filesystem etc).

I'm assuming, naively, that a solution to No. 1 would be to somehow overwrite anything happening here, and anything to do with the browser/DOM utils.
https://github.com/biwascheme/biwascheme/blob/master/src/library/js_interface.js

However, I'm not 100% familiar with the module format and libraries being used (my pre-ES6 experience is quite narrow) so I'm not sure if I'm missing a simpler solution to my problems, or if this functionality already exists within BiwaScheme.

(Otherwise, do you know of any other r5rs/r7rs-small browser-based or wasm schemes that might be appropriate? I was tempted to roll my own solution with [jsedn](https://github.com/shaunxcode/jsedn) and hack together a small interpreter, but Scheme addresses a lot of edge cases that I don't necessarily trust myself with)

Thanks!

**Comment by yhara** [comment]
The most dangerous functions are the ones which uses javascript `eval`. This is used only in library/js_interface.js so it can be disabled by commenting them out.

Another way to evaluate JavaScript code as string is to use Function (like `new Function("alert(1)")`). This technique is used in the  `js-load` function in library/webscheme_lib.js, which you also should disable.

Another concern is the `$` function in library/webscheme_lib.js because it has the same power as jQuery's `$`. Maybe you want to disable this too.

**Comment by ceigey** [comment]
Thank you @yhara for the direction!

I started looking into ways to quickly disable the specific functions with an already built version of BiwaScheme in Node, and noticed I can see everything in `BiwaScheme.CoreEnv`. So I will try deleting them from there once the library has already loaded.

I'm guessing what I need to use then is:

* `BiwaScheme.CoreEnv` - remove any functions I'm not confident about
* `BiwaScheme.TopEnv` - reset when I want to remove declared data, and also add data*
* `BiwaScheme.Symbols` - reset when I want to remove declared symbols (looks like I don't need to add symbols though, adding them to TopEnv seems to solve that problem)

Then I might be able to build up either an exclusion or inclusion list to keep in/out certain functions, and just run through that each time the page loads.

I'll close this issue and if anything specific comes up I guess I'll open a new one - thanks again!

_(Although I had a bit of a silly moment where I forgot the Node and Browser environments were different, so I was looking for `$` and `js-load` in the Node repl for a while, whoops!)_
