### ISSUE TITLE
Stop depending on jQuery

### ISSUE THREAD

**Issue by woxtu** [biwascheme/biwascheme#195]
Hi,

As the title says, I suggest to stop depending on jQuery in the webscheme library.
In 2020, many of jQuery's features can be replaced with vanilla JavaScript APIs, so I think jQuery is no longer necessary for us.

- Pros
  - File size can be reduced
  - Users can use the native DOM seamlessly
- Cons
  - Implementation becomes a little complicated
  - Break backwards compatibility

What do you think about that?

**Comment by yhara** [comment]
Good point. I want to keep backward compatibility as much as possible, so it is not possible to remove jQuery right now.
jQuery is only used in library/webscheme_lib.js, but problem is the `getelem` and `$` function, which is equivalent to jQuery's `$()`. This cannot be implemented without jQuery.

In the future (say, v1.0.0) I'm thinking of making jQuery optional; jQuery is not embedded in biwascheme.js and user can use webscheme_lib by loading jquery.js explicitly.

Until then, it would be nice if there is a way to build biwascheme.js without jQuery (or, without jQuery and webscheme_lib)

**Comment by woxtu** [comment]
Thank you for your reply.
I understand your opinion, and I'm looking forward to seeing the new version someday.
Close this issue for now.
