### ISSUE TITLE
Better logo

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#196]
I've designed better logo for your project, I think it's improvement. It was always bothered me that the Biwa logo was not that good.

Link to svg:
https://jcubic.pl/biwascheme_logo_new_curves.svg

![biwa-scheme-new](https://user-images.githubusercontent.com/280241/92089600-ac6b9900-edce-11ea-8200-48fe243f9d7d.png)

**Comment by yhara** [comment]
Great!😄   Should I update the website, or will you?

**Comment by jcubic** [comment]
I can update it.

**Comment by yhara** [comment]
Thanks! I've invited you as a committer so that you can commit it directly into master (i.e. you don't need to wait me to merge PR)

**Comment by jcubic** [comment]
I've merged my PR. Is website deployed automatically?

**Comment by yhara** [comment]
Yes. The green check left to the commit hash means deploy is done.

<img width="898" alt="スクリーンショット 2020-09-04 20 07 49" src="https://user-images.githubusercontent.com/12285/92232920-5724aa00-eeea-11ea-992a-4da24b3b1f81.png">

**Comment by jcubic** [comment]
You should also change the logo on organization I don't have access to settings, only owner have.

**Comment by yhara** [comment]
Oh that's right. I've updated it. https://github.com/biwascheme
