### ISSUE TITLE
Terminal REPL don't evaluate '#(1 2 3)

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#200]
Not sure why, yet but when executing `'#(1 2 3)` in terminal REPL it try to continue on next line and don't evaluate the expression.

Will try to fix the issue, I think that I'll just copy my latest REPL code from [LIPS Scheme](https://jcubic.github.io/lips/), since it works fine there.

**Comment by jcubic** [comment]
The problem is in unbalanced_parentheses function BiwaScheme parser return token `#(`. Adding another case fixes the issue.

@yhara  are there any other tokens that maye include open bracket `"("` or `"["?

**Comment by yhara** [comment]
> are there any other tokens that maye include open bracket 

Looking at src/system/parser.js, I found you can use `{}` for parenthesis (I didn't know that!)

```
/Users/yhara/Dropbox/proj/biwascheme % biwas
BiwaScheme version 0.7.1-pre1
try (+ 1 2), etc. (Ctrl-D to exit)
biwascheme> {}
()
biwascheme> #{}
#()
```

I think no one is actually using this though...

**Comment by jcubic** [comment]
I would not not care about those since they are not standard Scheme, but `[]` are handled, since some books about Scheme use them (same as Racket). If you have them in documentation I can add those as well. I was more thinking about some other tokens like `'#(` but those are just `(quote #(` same as backquote.

**Comment by yhara** [comment]
> If you have them in documentation I can add those as well

No, I'd rather remove the feature from the parser.
