### ISSUE TITLE
Console freeze with `#(1 2)` (Re: Cannot multiply matrices)

### ISSUE THREAD

**Issue by skeldoy** [biwascheme/biwascheme#21]
Tried doing a classic (\* #(1 2 3) #(1 2 3)) without success... Interpreter just stands blinking with ... prompt.. Have not looked into code yet, so I don't know if this ain't a feature or if it is a bug.

**Comment by alanthird** [comment]
The unbalanced_parentheses function doesn't recognise `#(` as an opening quote. A simple fix is just to add something like:

```javascript
case "#(": ++parentheses; break;
```

to the switch statement. MIT Scheme also has `#[` which would cause a similar issue, does Biwascheme have this or anything else similar?

**Comment by yhara** [comment]
@alanthird No, `[` or `#[` is not supported currently.
