### ISSUE TITLE
biwascheme.org without www. does not work

### ISSUE THREAD

**Issue by lassik** [biwascheme/biwascheme#218]
```
$ curl biwascheme.org
curl: (7) Failed to connect to biwascheme.org port 80: Operation timed out
```

curl www.biwascheme.org works fine.

**Comment by lassik** [comment]
```
$ host biwascheme.org
biwascheme.org has address 163.44.76.141

$ host www.biwascheme.org
www.biwascheme.org is an alias for biwascheme.github.io.
```

**Comment by yhara** [comment]
Thanks for reporting this, I didn't noticed.

I've changed DNS settings and http://biwascheme.org is accessible now.
https://biwascheme.org shows certification error, but I think this will be fixed [within 24 hours](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site).

**Comment by lassik** [comment]
Thanks!

The cert doesn't seem to work yet:

```
$ curl --location https://biwascheme.org
curl: (51) SSL: no alternative certificate subject name matches target host name 'biwascheme.org'
```

**Comment by yhara** [comment]
Hmm, according to this QA, this is expected situation. https://github.community/t/apex-domain-issued-invalid-certificate-with-github-pages-custom-domain/150184

Maybe fixed at some point in the future?
> The Pages team are aware of it though, and are looking to change this at some point in the future, though I can’t give an estimate on when this will happen as it’s not currently on our public roadmap.
