### ISSUE TITLE
`element-new` broken in v0.7.1

### ISSUE THREAD

**Issue by austinwk** [biwascheme/biwascheme#235]
## Description

Use of `element-new` in v0.7.1 throws: `nil is not defined [element-new]`.

This was not present in v0.7.0.

## Reproduction steps:

1. Download [biwascheme-0.7.1.js](https://raw.githubusercontent.com/biwascheme/biwascheme/master/release/biwascheme-0.7.1.js) (or [biwascheme-0.7.1-min.js](https://github.com/biwascheme/biwascheme/blob/master/release/biwascheme-0.7.1-min.js)).
2. Save the following html in the same directory:

    ```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Demo</title>
    </head>
    <body>
      <script src="biwascheme-0.7.1.js"></script>
      <script type="text/biwascheme">
        (element-new '(h1 "demo"))
      </script>
    </body>
    </html>
    ```

3. Load in the browser.

**Comment by yhara** [comment]
Thank you for reporting! Confirmed with git master.
