### ISSUE TITLE
One trouble in BiwaScheme.define_libfunc？

### ISSUE THREAD

**Issue by dasheng523** [biwascheme/biwascheme#242]
BiwaScheme version 0.7.2

I try to put the following code in `js_ interface.js`, and then `npm run build`.
```
define_libfunc("promise-wait", 1, 1, function(ar){
  var p = ar[0];
  return new Pause(function(pause){
    p.then(function(rs) {
      pause.resume(rs)
    });
  });
});
```

Here are two test files:
```
- a.ss
(load "b.ss")

- b.ss
(display (promise-wait (js-eval "Promise.resolve('666')")))
```

When running `npx biwas a.ss`, `display` has no output.

If the content of b.ss is put into a.ss, the running result is correct.

```
- a.ss
;;(load "b.ss")
(display (promise-wait (js-eval "Promise.resolve(\"666\")")))
```
`display` output 666

So, what happened in `load` or `define_libfunc`?

**Comment by yhara** [comment]
Hmm, interesting question. I'll take a look.

**Comment by yhara** [comment]
I think I've found the reason -- the `load` function creates new `Interpreter` via `run` and the continuation stored in the stack is lost.

**Comment by dasheng523** [comment]
What do I need to do? I plan to split a single code file into multiple files, but this problem blocked me.

**Comment by yhara** [comment]
I'm trying to fix this. I think I can make a Pull Request in a few days.

**Comment by yhara** [comment]
Done! you can try it now.

**Comment by dasheng523** [comment]
Thanks, I have tried it, but it seems to cause other problems.

**Comment by jcubic** [comment]
@dasheng523 did you check the version on GitHub instead of NPM that may not got released yet?
