### ISSUE TITLE
Unnecessary use of `with`?

### ISSUE THREAD

**Issue by didhe** [biwascheme/biwascheme#26]
The biwascheme library code uses `with` in several places, generally in conjunction with `define_libfunc`. Given the [concerns involved](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with) in use of `with` (the ambiguity problem came up for me earlier why trying to hack on the js interface...), I'd think that, in the long term, it could be useful to refactor the `with`s out.

(Tangentially, I'd also super-appreciate it if a future biwascheme would conform to ES5 strict mode, but that _isn't_ necessarily feasible.)

**Comment by yhara** [comment]
Should be fixed by #160
