### ISSUE TITLE
Doesn't support space symbol

### ISSUE THREAD

**Issue by AiziChen** [biwascheme/biwascheme#267]
in scheme, this syntax is valid:
```scheme
(display '|hello, world|)
```
but biwaScheme throw the exception:
`Error: execute: unbound symbol: "world|" []`

**Comment by jcubic** [comment]
It's part of R7RS that is not yet supported. BiwaScheme is not R7RS Scheme.

**Comment by yhara** [comment]
> BiwaScheme is not R7RS Scheme

BiwaScheme aims to implement R7RS-small as much as possible, so this is both feature request and bug report... anyway I'll try implementing it (I think it's not so difficult because string literals already can contain spaces.)
