### ISSUE TITLE
Add (remainder) to the sicp on BiwaScheme website page

### ISSUE THREAD

**Issue by cgbarros** [biwascheme/biwascheme#277]
In section 1.2 of SICP they use the procedure `remainder`, which in Biwa should be the same as `mod`. Can you add

`(define (remainder a b) (mod a b))`

to the page?

**Comment by cgbarros** [comment]
Correction: it should be the same for positive integers, which I think it's the case every time in SICP.

**Comment by jcubic** [comment]
There is also a need for `modulo` function, it's not the same as JavaScript %.
it took me a while to understand how it works.

Scheme module works like this (taken from my Scheme interpreter):

```scheme
(define (modulo a b)
  "(modulo a b)

   Function return modulo operation on its arguments."
  (typecheck "modulo" a "number" 1)
  (typecheck "modulo" b "number" 2)
  (- a (* b (floor (/ a b)))))
```

**Comment by jcubic** [comment]
Also not that you can use point free style:

```scheme
(define remainder mod)
```

**Comment by yhara** [comment]
Hmm R7RS Small defines six functions (and three aliases) for division. I'll try implementing them.
```scheme
(floor/ n n )
(floor-quotient n1 n2)
(floor-remainder n1 n2) == (modulo n1 n2) 
(truncate/ n1 n2)
(truncate-quotient n1 n2) == (quotient n1 n2)
(truncate-remainder n1 n2 ) == (remainder n1 n2)
```
