### ISSUE TITLE
Problem with r6rs record type predicates when using inheritance

### ISSUE THREAD

**Issue by meta-circular** [biwascheme/biwascheme#294]
There is a problem with record type predicate if a parent record type is used.

`(define-record-type point (field x y))`
`(define-record-type cpoint (parent point) (field c))`
`(define cp (make-cpoint 1 2 "red"))`
`(cpoint? cp)` => `#t`
`(point? cp)` => `#f`, while expected result was `#t`.

**Comment by yhara** [comment]
Confirmed with sagittarius-scheme 0.9.9.

```
% cat a.scm
(import 
  (rnrs records syntactic (6))
  (rnrs records procedural (6))
  (rnrs records inspection (6)))
(define-record-type point (fields x y))
(define-record-type cpoint (parent point) (fields c))
(define cp (make-cpoint 1 2 "red"))
(display (cpoint? cp))
(display (point? cp))
% sagittarius a.scm
#t#t
```
