### ISSUE TITLE
Extra whitespace in website terminal

### ISSUE THREAD

**Issue by yhara** [biwascheme/biwascheme#299]
When I open https://www.biwascheme.org/ and type something in the terminal, there is extra space after the prompt and it disappears when I hit Enter.

## Screenshot

https://gyazo.com/5844c30a51aa9784971f39c047519334

## Environment

- browser: Mac Chrome
- jquery.terminal: [the one on the CDN](https://github.com/biwascheme/biwascheme/blob/master/website/_footer.html)

**Comment by jcubic** [comment]
I will test it in BrowserStack it looks like a font issue. It works fine in Chrome Linux but the font is different. Will investigate.

**Comment by jcubic** [comment]
I've tested on BrowserStack Chrome 107/MacOS and it works fine, but the font is different. Please check what kind of font you have installed, the library uses monospace.

Your screenshot looks different than what I have in browserstack, where mospace font have serifs your font looks like Arial or Mac alternative.

![Peek 2022-11-23 16-45](https://user-images.githubusercontent.com/280241/203589176-45845dac-e1fd-4009-a879-8d016c67c947.gif)

**Comment by yhara** [comment]
Thanks for investigating. Confirmed there is no problem with Mac Firefox and Mac Safari.

**Comment by yhara** [comment]
Looks like this is a long-time issue of Chrome + Mac + Japanese.
https://bugs.chromium.org/p/chromium/issues/detail?id=75585

**Comment by jcubic** [comment]
I'm not sure if I will be able to test Japanese font, but maybe you can create a hack that will fix it, I can even integrate it with the library. The command line use every character as single span and you can set `width: 1ch` on that span. There is already code that handles Japanese and Chinese characters if you include wcwidth library, so it set 2ch for those characters. But I've only tested this on Linux+Japanese/Chinese.

I will check if I can test this setup on BrowserStack if not I will contact support if there is a way.

**Comment by yhara** [comment]
Another possible workaround is to specify some actual font name available on Mac [here](https://github.com/jcubic/jquery.terminal/blob/master/css/jquery.terminal.css#L263) like `font-family: Menlo, monospace;` (I'm not sure what `var(--font, ..)` does here so it may not be safe though.)

**Comment by jcubic** [comment]
It's a [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) (known as CSS variables), so you can change the font without touching the library CSS:

```css:
:root {
  --font: Menlo, monospace;
}
```

**Comment by yhara** [comment]
> so you can change the font without touching the library CSS

Thank you, I've confirmed by this issue is fixed by #304.
