### ISSUE TITLE
How to embed it into a webpage?

### ISSUE THREAD

**Issue by mancuoj** [biwascheme/biwascheme#313]
Hello,

I am interested in using your scheme interpreter repository on Github, but I am not sure how to embed it into a webpage like the [CS61A textbook](http://composingprograms.com/pages/32-functional-programming.html). Could you please provide some guidance on how to do this?

I was wondering if I should use an iframe or if there is another technique that can be used? Any help or suggestions would be greatly appreciated.

Thank you for your time and for creating this valuable resource.

**Comment by jcubic** [comment]
There was a library that was adding exactly this that used BiwaScheme and a bunch of other programming languages, but I don't remember that name and I can't find it right now.

**Comment by jcubic** [comment]
I was able to find it, it was [Klipse](https://github.com/viebel/klipse).

**Comment by mancuoj** [comment]
> I was able to find it, it was [Klipse](https://github.com/viebel/klipse).
I'll try it, thank you!
