### ISSUE TITLE
404 for How to build BiwaScheme

### ISSUE THREAD

**Issue by soegaard** [biwascheme/biwascheme#321]
This link shows an 404 error.

https://www.biwascheme.org/doc/dev/build.html

It is listed at the bottom of:

https://www.biwascheme.org/doc/index.html

**Comment by yhara** [comment]
Thanks for your report, I am not sure why only `build.html` in the `dev` directory is 404... I will investigate.

**Comment by yhara** [comment]
I found out why, the file was named "bulid".html. :flushed:
