### ISSUE TITLE
Error for unbalanced parentheses

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#330]
This throws a weird error:

```javascript
var bscheme = new BiwaScheme.Interpreter(function(e, state) {
   console.error(e);
}); 
bscheme.evaluate("(display 10))") 
```

> Error: execute: unbound symbol: "" []

It should throw an error about an invalid character. I have the same issue in my Scheme interpreter which has a parser inspired by BiwaScheme.

**Comment by yhara** [comment]
fixed by https://github.com/biwascheme/biwascheme/pull/344.
