### ISSUE TITLE
psyntax

### ISSUE THREAD

**Issue by asolove** [biwascheme/biwascheme#35]
I am working on a project using Scheme in the browser. Biwa seems to check off all the other requirements except for proper r6 syntax support. I am therefore interested in getting the [portable syntax implementation](http://www.cs.indiana.edu/l/www/chezscheme/r6rs-libraries/) working on Biwa if possible.

Before I start, I am curious if anyone else has tried, would like to offer advice, or can provide guidance for eventually landing it as a patch to Biwa if I succeed.

Thanks!

**Comment by theblacksquid** [comment]
@asolove  Was this ever resolved, hence the closure?

**Comment by asolove** [comment]
@theblacksquid Nope, but since I haven't actively pursued it in a long time, I wanted to close the issue so no one expected any progress from me.
