### ISSUE TITLE
error "x.cdr.to_array is not a function" for "(1 . 2)"

### ISSUE THREAD

**Issue by mikecat** [biwascheme/biwascheme#37]
When I run a ill-formed expression

    (1 . 2)

(not ````'(1 . 2)```` , which is correct syntax) on "Try it now" on the web page,
I get a error

    x.cdr.to_array is not a function
    [USER]: http://www.biwascheme.org/release/biwascheme.js: x.cdr.to_array is not a function

in red characters and the interperter stops.

I think that it is caused on 557th line of ````src/system/interperter.js```` , which is

            var expanded_cdr = BiwaScheme.array_to_list(
                                 _.map(x.cdr.to_array(),
                                       function(item){ return expand(item, flag); }));

and that you should check if ````x.cdr.to_array```` is available.

**Comment by yhara** [comment]
@mikecat sorry for being late. I just confirmed your patch.

Now BiwaScheme throws error for expressions like `(1 . 2)`. Thanks for your contribution.
