### ISSUE TITLE
remove-handler! does not seem to work

### ISSUE THREAD

**Issue by camilledalmeras** [biwascheme/biwascheme#41]
Hello,

Scheme (and programming) novice here, so please forgive any obvious mistake.
I tried the following code in BiwaScheme's REPL:

(define say-hello
  (lambda ()
    (alert "Hi there!")))

(add-handler! (getelem "body") "click" say-hello)
(remove-handler! (getelem "body") "click" say-hello)

Upon clicking the page, an alert shows nonetheless. Am I missing something?

Thank you.

**Comment by yhara** [comment]
Hi,
Sorry for late reply.

You need to save the result of `add-handler!` and pass it to `remove-handler!`, like this:

```scheme
(define handler (add-handler! (getelem "body") "click" say-hello))
(remove-handler! (getelem "body") "click" handler)
```

Recently I'm writing reference of BiwaScheme. Please feel free to ask me if you find something unclear.
http://www.biwascheme.org/doc/reference.html#browser
