### ISSUE TITLE
Chapter 19 R5RS compatibility - delay, force 

### ISSUE THREAD

**Issue by gitmh** [biwascheme/biwascheme#55]
I found: (delay expression), (force promise) and (make-promise (lambda () expression))
in the source code but are they already implemented in biwascheme? 

I found a working implementation of those syntax elements in https://bluishcoder.co.nz/jsscheme/ but I have no idea how to extend biwascheme accordingly.

Would be a really help to have those functions for creating streams and similar concepts.

**Comment by yhara** [comment]
> are they already implemented in biwascheme?

No, but I'm working on it and will be included in the next release.
I've just added `delay` and `force` onto git master.

**Comment by gitmh** [comment]
Thank you very much yhara for adding this. Looking forward for the next release :-)
