### ISSUE TITLE
define-record-type syntax

### ISSUE THREAD

**Issue by lukedmor** [biwascheme/biwascheme#56]
Is there a reason `define-record-type` doesn't follow the spec?
It should look like:

```scheme
(define-record-type my-type
  (make-my-type bar baz)
  my-type?
  (bar get-bar set-bar!)
  (baz get-baz))
```

but instead, it's like:

```scheme
(define-record-type my-type
  (fields (mutable bar) (immutable baz)))
```

I can't port Scheme code, and anyone who works with what I have in Biwascheme would have to figure out this syntax.

**Comment by yhara** [comment]
Currently, `define-record-type` of BiwaScheme is based on R6RS, not R7RS. See below for the specification.
http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-7.html#node_chap_6

**Comment by lukedmor** [comment]
@yhara Thanks for responding so quickly. I was looking at the MIT/GNU Scheme reference [here](http://www.gnu.org/software/mit-scheme/documentation/mit-scheme-ref/define_002drecord_002dtype-_0028SRFI-9_0029.html#define_002drecord_002dtype-_0028SRFI-9_0029). I guess it's also in R7RS. Are there any plans to switch to this spec?

**Comment by yhara** [comment]
> I was looking at the MIT/GNU Scheme reference here. I guess it's also in R7RS. 

It looks like MIT/GNU Scheme implements [SRFI-9](http://srfi.schemers.org/srfi-9/srfi-9.html). I'm not sure it is identical to R7RS Records.

> Are there any plans to switch to this spec?

In the long term, yes. But I'd like to support R7RS records without losing backward compatibility (as much as possible), and thinking how to achive this.

Until that, you can use R7RS records in BiwaScheme with this macro:

```scheme
(define-macro (define-record-type-r7rs record-name ctor-spec pred-name . field-specs)
  (let1 fields (map (lambda (fs)
                      (if (= 2 (length fs))
                        (cons 'immutable fs)
                        (cons 'mutable fs)))
                    field-specs)
    `(define-record-type
      (,record-name ,(car ctor-spec) ,pred-name)
      (fields ,@fields))))
    
; Example (taken from R7RS p.27)
(define-record-type-r7rs <pare>
  (kons x y)
  pare?
  (x kar set-kar!)
  (y kdr))

(display (kar (kons 1 2)) ;=> 1
```

**Comment by lukedmor** [comment]
Thanks!
