### ISSUE TITLE
Unexpected output on functions

### ISSUE THREAD

**Issue by theblacksquid** [biwascheme/biwascheme#64]
I've been trying to build an n*n tic-tac-toe game with Biwascheme, and lately, I've been encountering this weird issue where several values are getting replaced by 
``` 
#("argument" #("refer-global"  #"con
s" #("shift" 2 #("tco_hinted_apply"))))
```
and cause random errors when I test. I'm running them all using biwascheme 0.6.4 and Firefox  47

Two examples include:

```
(define (make-list n val)
   (if (zero? n)
       '()
       (cons val (make-list (- n 1)))))
```
and for a non-trivial example: <a href="https://gist.github.com/theblacksquid/204b43051078a548b7c5e8589f4f6fe8#file-grid-functions-scm-L60">this</a>

Tested the above, and does not produce errors in Gambit-in-the-browser.

EDIT: Clarity, details and links

**Comment by yhara** [comment]
Wow, this is really weird behavior. Thanks for reporting. I'll investigate.

**Comment by yhara** [comment]
@theblacksquid In the example

```scm
(define (make-list n val)
   (if (zero? n)
       '()
       (cons val (make-list (- n 1)))))
```

>        (cons val (make-list (- n 1)))))

this line should be

>        (cons val (make-list (- n 1) val))))

Then `(make-list 2 #t)` returns `(#t #t)` as expected.

**Comment by theblacksquid** [comment]
sorry about that, I couldn't see that it was an error in my own code, and thanks for pointing that out ^ _ ^
