### ISSUE TITLE
Bitwise procedures

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#65]
In BiwaScheme 0.5.4.2 used [here](http://terminal.jcubic.pl/examples.php#dterm) there are defined procedures `|` `&` `>>` `<<` but they are undefined in demo on http://www.biwascheme.org/
where they removed from biwascheme?

**Comment by yhara** [comment]
@jcubic I found http://terminal.jcubic.pl/js/biwascheme.func.js has these functions, so I think they are just not part of BiwaScheme :-)
