### ISSUE TITLE
Thanks you for this great scheme interpreter

### ISSUE THREAD

**Issue by viebel** [biwascheme/biwascheme#67]
I have integrated biwascheme into KLIPSE.
Take a look here: http://blog.klipse.tech/scheme/2016/09/11/scheme-tutorial-1.html

**Comment by yhara** [comment]
Great! I'm always happy when I see people made something with BiwaScheme.

@viebel By the way, `###Symbols` in the post should be `### Symbols`

**Comment by viebel** [comment]
Thanks @yhara  I fixed the typo.

Can you give me a couple of code examples of how to deal with complex numbers, rational numbers, infinity, inexact numbers etc...

I would like to add i to the blog post?

**Comment by yhara** [comment]
(cont: #68)
