### ISSUE TITLE
reactjs interop

### ISSUE THREAD

**Issue by amirouche** [biwascheme/biwascheme#73]
I'm looking for example code that use libraries like reactjs. That is javascript libraries that are declare the view and patch the dom to render it.

Thanks!

**Comment by amirouche** [comment]
I am basically looking for bindings of libraries like https://github.com/snabbdom/snabbdom

**Comment by amirouche** [comment]
I made [a post on the mailling list](https://groups.google.com/forum/#!topic/biwascheme/URurpsiLrr0) about the subject, let's follow that there.

**Comment by amirouche** [comment]
It pasted the latest version of my understanding of the subject in [forward.scm](https://amirouche.github.io/forward.scm/).

The end result of this is that, there is `(create-app root init routes). The `ROOT` is the handle the browser gives to use for displaying stuff on screen. That's bascially the screen d/ct/onary. It's tree datastructure made of node with styles and a function called event handler. Event handlers are associated on per node using some kind of med/ator pattern that bubble up the event in the tree (which is controllable by user code). `INIT` is a procedure will initiate the seed data of the app, that's the RAM of the app. `ROUTES` allows to control in particular browser url. It's allow in turns to player with the bower history.

**Comment by amirouche** [comment]
Controllers, get a snapshot of the the model (data) and trigger a particular possibly long process, but not as long as to go out of sync with the UI. If you can go out of sync, you must use `spawn`.

**Comment by theblacksquid** [comment]
This is a godsend. Thank you! I've been using biwascheme for so long and just using the built-in element-new and plugging in callbacks after they render.

**Comment by amirouche** [comment]
BiwaScheme has the necessary features to work with reactjs (or preact). Sorry for the dead links in the previous posts, here is backup link: https://github.com/amirouche/forward.scm, also look into https://github.com/amirouche/ff.js. Here is another demo using Gambit https://github.com/pre-srfi/webui.

ReactJS 16+ with hooks offer an alternative or complementary approach. I prefer `forward.scm` tho. On the topic of ReactJS, look into ReactQuery.

In my opinion, there is too much fuss around frontend / gui dev to recommend or bless one particular library / framework / approach inside biwascheme.

I will close the issue, because it was a question and not a bug or feature request.

**Comment by jcubic** [comment]
The way BiwaScheme is created requires a lot of work to make it work with ReacJS (or any other library). In contrast with My Scheme implementation, It was trivial to add ReactJS support, See this demo https://codepen.io/jcubic/pen/JjKbqWd the core of my Scheme interpreter is to allow running any JavaScript, so you don't need to add support for any library because all JavaScript libraries are supported.

**Comment by amirouche** [comment]
I considered using LIPS (which appeared as first result in duckduckgo). Basically, I know biwascheme quirks, and I need to get going.
