### ISSUE TITLE
ReferenceError: Interpreter is not defined

### ISSUE THREAD

**Issue by jcubic** [biwascheme/biwascheme#76]
There is errror in `BiwaScheme.define_scmfunc` the code look like this:

```javascript
BiwaScheme.define_scmfunc = function(fname, min, max, str){
  (new Interpreter).evaluate("(define "+fname+" "+str+"\n)");
}
```
and it throw exception, it should be `BiwaScheme.Interpreter`

**Comment by yhara** [comment]
Fixed (and added a test). Thanks for reporting.
