### ISSUE TITLE
no sorting function

### ISSUE THREAD

**Issue by amirouche** [biwascheme/biwascheme#77]
Right now there is no sorting function that support a particular comparator.

How can this be fixed?

**Comment by yhara** [comment]
Actually BiwaScheme has functions `list-sort/comp`, `vector-sort/comp` and `vector-sort/comp!` which can take a  comparator but have some restrictions. You can use them for simple cases.

```scm
; OK. Returns '(1 2 3)
(list-sort/comp > '(3 1 2))

; NG: Comparator must not refer to free variable (`x` here)
(define (f x)
  (list-sort/comp
    (lambda (a b) x)
    '(3 1 2)))

; NG: Comparator must not include setTimeout (`sleep`, etc.)
(list-sort/comp (lambda (a b) (sleep 1) (> a b)) '(3 1 2))
```

**Comment by yhara** [comment]
@amirouche Fixed :-)

**Comment by amirouche** [comment]
Neat! thx!
