### ISSUE TITLE
[BUG] "Not a Function" error is called when (load)'ing .scm files on Firefox 50

### ISSUE THREAD

**Issue by theblacksquid** [biwascheme/biwascheme#79]
I have two files, index.html and index.scm. When I tried `load`ing the .scm file, i get the following errors in the Firefox console:

    syntax error  index.scm:1:1
    TypeError: txt.replace is not a function[Learn More]  biwascheme.js:1588:15

Making sure it was not my own code I just put `(console-log "hello world")` in index.scm and between the `<script src='biwascheme.js'>` tags. Same symptoms.

The program works as expected in chrome, though.

**Comment by yhara** [comment]
I've downloaded Firefox and could reproduce the error.

> TypeError: txt.replace is not a function

However, I got an error in Chrome too:

> XMLHttpRequest cannot load file:///Users/yhara/Dropbox/proj/biwascheme/,/79-load-err-firefox/index.scm. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

One way to avoid this error is to run a local http server that serves index.html and index.scm. And in this way, it worked as expected in Firefox too.

**Comment by yhara** [comment]
Ok, the error in Firefox is fixed with the patch above.
