### ISSUE TITLE
element-toggle-class-name

### ISSUE THREAD

**Issue by ceving** [biwascheme/biwascheme#80]
When I use the function with the bang, I still get the warning:

    (element-toggle-class-name! ($ "body") "x")

> element-toggle-class-name is deprecated and will be removed in BiwaScheme 1.0. Please use element-toggle-class-name! instead

Tested with Firefox 50.0.2 and the repl http://www.biwascheme.org/

Same for `element-add-class-name!`.

**Comment by yhara** [comment]
Fixed. Thanks for reporting.
