### ISSUE TITLE
`case-lambda` returns `undefined is not a function` error

### ISSUE THREAD

**Issue by theblacksquid** [biwascheme/biwascheme#81]
Using `case-lambda` like in the following code:

```
(define somefn
  (case-lambda
    ((x) (print "one argument"))
    ((x y) (print "two arguments"))))
```

returns the following error in Nodejs (v7.2.0):

```
Error: undefined is not a function [somefn]
```

Tested with the [Biwascheme REPL](http://www.biwascheme.org./demo/repl.html), there was no response at all.

Confirmed that expected behavior is seen in Gauche 0.9.4

**Comment by yhara** [comment]
Fixed. (actually it was not broken, just not implemented 😳 )

**Comment by theblacksquid** [comment]
Yay! Thank you for patching this up on a holiday. Happy Holidays to you and yours!
