### ISSUE TITLE
Drop underscore.string from dependencies?

### ISSUE THREAD

**Issue by camilledalmeras** [biwascheme/biwascheme#85]
Hello,

After building biwascheme-plain.js and deploying my Scheme application, a 404 in the browser console made me realize I had forgotten to include underscore.string.js along with the other scripts. To my surprise, my program still worked fine, so I fiddled a bit with BiwaScheme's makefile to remove underscore.string, proceeded to build, then ran the test suite without a hitch. I grepped biwascheme's source code, and there seems to be no reference to underscore.string's functions.

I may be mistaken, but at this point it seems underscore.string is not needed anymore. If you confirm this is the case, I will be happy to submit a pull request to prune underscore.string from BiwaScheme.

Thank you,

Camille d'Alméras

**Comment by yhara** [comment]
Hello,

According to the commit which added underscore.string, it seems that it is used [here](https://github.com/biwascheme/biwascheme/blob/master/src/library/webscheme_lib.js#L292).
So the real problem is that this library function is not covered by the tests...
Thank you for pointing it out anyway :-)

**Comment by camilledalmeras** [comment]
Hello,

I just skimmed the docs for both underscore.js and underscore.string and it seems to me that the "escape" function used in webscheme_lib.js at the line you referred to pertains to the former. Please see [http://underscorejs.org/#escape](url) and contrast with [http://epeli.github.io/underscore.string/#escapehtml-string-gt-string](url)

As always, I may well be mistaken as I am not a developer by trade, but in this particular instance I feel fairly confident about dropping underscore.string.

Thanks,

Camille d'Alméras

**Comment by yhara** [comment]
> Please see http://underscorejs.org/#escape and contrast with http://epeli.github.io/underscore.string/#escapehtml-string-gt-string

Oh I confused #escape and #escapeHtml. Thanks.

What I should check was the ocurrence of `_s` and `_.str`. As a result, I found some uses of `_.str.truncate` (e.g. [here](https://github.com/biwascheme/biwascheme/blob/master/src/system/_writer.js#L16)) so it seems that we still need underscore.string (and these part are not covered with unit test).

**Comment by camilledalmeras** [comment]
You are absolutely right of course, apologies for the noise. My grep skills must be as weak as my interest in javascript ;)
