### ISSUE TITLE
load function XML parse error and fix!

### ISSUE THREAD

**Issue by jankovicsandras** [biwascheme/biwascheme#88]
Hi,

I found a small problem with the `load` function: XML parse error (not well-formed) when loading files with file:// protocol. This is actually more like a jQuery error, not biwascheme specific, but I found a solution here:

https://stackoverflow.com/questions/1828228/why-does-jquery-insist-my-plain-text-is-not-well-formed

Changing the [load function in webscheme_lib.js](https://github.com/biwascheme/biwascheme/blob/master/src/library/webscheme_lib.js#L302) fixed the problem:

```javascript
  //
  // load from network
  //
  define_libfunc("load", 1, 1, function(ar, intp){
    var path = ar[0];
    assert_string(path);
    var intp2 = new Interpreter(intp);
    return new BiwaScheme.Pause(function(pause){
    	
      $.ajax({
    	url: path,
    	type:'GET',
        dataType: 'text',
        mimeType: 'text/plain; charset=x-user-defined',
        cache: false,
        isLocal: true,
        success: function(data) {
          // create new interpreter not to destroy current stack.
          intp2.evaluate( data, function(){ return pause.resume(BiwaScheme.undef); } );
        },
        error: function() {
          throw new Error("load: network error: failed to load "+path);
        }
      });
      
    });
  });
```

**Comment by yhara** [comment]
Thanks for reporting! Before applying the patch, I want to reproduce the error on my machine.
However, I got different error message on Chrome and got no error on Safari/Firefox. 

- Chrome: got error: `XMLHttpRequest cannot load file:///Users/yhara/proj/biwascheme/,/88-load-xml/a.scm. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`
- Safari: no error
- Firefox: no error

Which browser did you use when you got the error?

Here are the files I used.

### index.html

```html
<body>
<div id="bs-console"></div>
<script src="biwascheme.js">
(load "file:///Users/yhara/(snip)/a.scm")
</script>
```

### a.scm

```scheme
(alert "ok")
```

**Comment by jankovicsandras** [comment]
Hi,

I get the error with Firefox 52.0.2 (32 bit) on Windows 7. To be clear: the error does not stop the biwascheme program, it's just a jQuery Ajax related error message on the console:

![XML Parsing error](https://raw.githubusercontent.com/jankovicsandras/misc/master/biwaissue/xml_parsing_error_syntax_error.jpg)

The error message disappears after the above mentioned changes.

Here are the test files (based on your test): [https://github.com/jankovicsandras/misc/tree/master/biwaissue](https://github.com/jankovicsandras/misc/tree/master/biwaissue)

**Comment by yhara** [comment]
Thanks! Confirmed the issue.
