### ISSUE TITLE
"Biwa Scheme for Mobile" demo page does not work

### ISSUE THREAD

**Issue by mituharu** [biwascheme/biwascheme#93]
The "Biwa Scheme for Mobile" demo page at http://www.biwascheme.org/website/i.html does not print the evaluation result.
I tried it with Safari on iOS 10.3.1 and macOS 10.12.4.
JavaScript Console on the latter says "ReferenceError: Can't find variable: puts".

**Comment by yhara** [comment]
@mituharu Thanks, I did not notice it.
