### ISSUE TITLE
My clicker gets very slow

### ISSUE THREAD

**Issue by amirouche** [biwascheme/biwascheme#94]
Have  a look at my game, play a bit and fire a lot of next turns at some points the counters get slow, the browser lag. It is reproduced with firefox 45 (on debian stable) but not on firefox 52 (latest ubuntu)

https://amirouche.github.io/space-exploration/

**Comment by yhara** [comment]
Tried with my MacBook (OS 10.12.4).

- Chrome 57: gets slow
- Firefox 52: gets slow
- Safari 10.1: never gets slow

Hmm, this is interesting 😐

**Comment by amirouche** [comment]
I don't reproduce with firefox 53.0b5. How big is the counter?

I will try to create a small snippet that reproduce the bug hopefully without the need to click.

**Comment by yhara** [comment]
> How big is the counter?

Not so big. When I click the 'next turns' button again and again quickly, the counter shows up like 5, 15, 35, 90, 130.
