### ISSUE TITLE
Update to version 0.6.8 on npm

### ISSUE THREAD

**Issue by iliocatallo** [biwascheme/biwascheme#99]
Hi,

The latest version available on npm seems to be 0.6.7, as opposed to the more recent 0.6.8. Would it be possible to update it? 

Thank you!

**Comment by yhara** [comment]
Oops, I just forgot to type `npm publish`. Thanks for noticing! 
Uploaded 0.6.8 now.
https://www.npmjs.com/package/biwascheme
